# Generated by Django 3.2.22 on 2023-10-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(default='2023-12-12'),
            preserve_default=False,
        ),
    ]
